version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: hackathon_db
    environment:
      POSTGRES_USER: hackathon_user
      POSTGRES_PASSWORD: hackathon_password
      POSTGRES_DB: hackathon_db
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
